### ISSUE TITLE
Wrong time inserted on database

### ISSUE THREAD

**Issue by kleytonroan** [jeremykenedy/laravel-time-tracker#1]
I'm brasilian, and here the time is in 24hrs.
When i put for example, in 10:00 and end 12:00, in database the end time change, and I can´t understand why, here timezone is +3, and that's the time added always, I can´t figured out where is the problem
![img3](https://user-images.githubusercontent.com/19601133/27913990-3141ca12-6238-11e7-8f70-89ee4d8e19d2.jpg)
.

In time.saveTime, the values are correct, but laravel receive always +3 hours.
I installed barryvdh/laravel-debugbar, put in TimeEntriesController@store a debug message:

`public function store()
 {
        $data = Request::all();

        Debugbar::debug($data);

        $timeentry = new TimeEntry();
        $timeentry->fill($data);
        $timeentry->save();
 }`

this images show my problem
![img1](https://user-images.githubusercontent.com/19601133/27913641-2ee46988-6237-11e7-8c85-16a93ed9bce3.jpg)
![img2](https://user-images.githubusercontent.com/19601133/27913642-2eecdb40-6237-11e7-808e-8ee0e774dbe3.jpg)
![img3](https://user-images.githubusercontent.com/19601133/27914142-a6314a82-6238-11e7-936d-cb1b356b84c3.jpg)

**Comment by tschoffelen** [comment]
Seems like the javascript library that is responsible for letting you select times always return the output in UTC. And that's great, because that's the way you should save it into the database so that the data is not relative to your timezone. 

Unfortunately, it seems the application then doesn't convert back to your timezone when retrieving it from the database. I think this might be a problem in your configuration. Did you change the [timezone in config/app.php](https://github.com/jeremykenedy/laravel-time-tracker/blob/master/config/app.php#L55)? For you, I think this should have the value `America/Sao_Paulo `, but not totally sure about the way Brazil is divided into timezones. 

[Here](http://php.net/manual/en/timezones.america.php#118862) is a list of all valid timezone values for Brazil, listed by state.
